/*
 * WSO2 API Manager - Publisher API
 * This specifies a **RESTful API** for WSO2 **API Manager** - Publisher.  Please see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.0.4/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification. 
 *
 * OpenAPI spec version: 0.11.0
 * Contact: architecture@wso2.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api.publisher;

import io.swagger.client.ApiException;
import io.swagger.client.model.publisher.Wsdl;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for WsdlIndividualApi
 */
@Ignore
public class WsdlIndividualApiTest {

    private final WsdlIndividualApi api = new WsdlIndividualApi();

    
    /**
     * Get a wsdl correspond to a API
     *
     * This operation can be used to retrieve a particular global mediation policy. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apisApiIdWsdlGetTest() throws ApiException {
        String apiId = null;
        String accept = null;
        String ifNoneMatch = null;
        String ifModifiedSince = null;
        Wsdl response = api.apisApiIdWsdlGet(apiId, accept, ifNoneMatch, ifModifiedSince);

        // TODO: test validations
    }
    
    /**
     * Add wsdl
     *
     * This operation can be used to add a wsdl to an existing API. wsdl definition to be updated is passed as a form data parameter &#x60;wsdlDefinition&#x60;. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apisApiIdWsdlPostTest() throws ApiException {
        String apiId = null;
        Wsdl body = null;
        String contentType = null;
        String ifMatch = null;
        String ifUnmodifiedSince = null;
        api.apisApiIdWsdlPost(apiId, body, contentType, ifMatch, ifUnmodifiedSince);

        // TODO: test validations
    }
    
}
