/*
 * WSO2 API Manager - Admin
 * This document specifies a **RESTful API** for WSO2 **API Manager** - Admin Portal.  It is written with [swagger 2](http://swagger.io/). 
 *
 * OpenAPI spec version: 0.11.0
 * Contact: architecture@wso2.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api.admin;

import io.swagger.client.ApiException;
import io.swagger.client.api.admin.MediationPolicyApi;
import io.swagger.client.model.admin.Mediation;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for MediationPolicyApi
 */
@Ignore
public class MediationPolicyApiTest {

    private final MediationPolicyApi api = new MediationPolicyApi();

    
    /**
     * Upload a global mediation policy
     *
     * This operation can be used to upload a global mediatoin policy to the registry. The file to be uploaded should be given as a form data parameter &#x60;file&#x60;. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void policiesMediationPostTest() throws ApiException {
        Mediation body = null;
        String contentType = null;
        String ifMatch = null;
        String ifUnmodifiedSince = null;
        Mediation response = api.policiesMediationPost(body, contentType, ifMatch, ifUnmodifiedSince);

        // TODO: test validations
    }
    
}
