/*
 * WSO2 API Manager - Store
 * This specifies a **RESTful API** for WSO2 **API Manager** - Store.  Please see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.0.4/components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/resources/store-api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification. 
 *
 * OpenAPI spec version: 0.11.0
 * Contact: architecture@wso2.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api.store;

import io.swagger.client.ApiException;
import io.swagger.client.api.store.TagCollectionApi;
import io.swagger.client.model.store.TagList;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for TagCollectionApi
 */
@Ignore
public class TagCollectionApiTest {

    private final TagCollectionApi api = new TagCollectionApi();

    
    /**
     * Get all tags 
     *
     * This operation can be used to retrieve a list of tags that are already added to APIs. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void tagsGetTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        String xWSO2Tenant = null;
        String accept = null;
        String ifNoneMatch = null;
        TagList response = api.tagsGet(limit, offset, xWSO2Tenant, accept, ifNoneMatch);

        // TODO: test validations
    }
    
}
