/*
 * WSO2 API Manager - Store
 * This specifies a **RESTful API** for WSO2 **API Manager** - Store.  Please see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.0.4/components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/resources/store-api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification. 
 *
 * OpenAPI spec version: 0.11.0
 * Contact: architecture@wso2.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api.store;

import io.swagger.client.ApiException;
import io.swagger.client.api.store.ThrottlingTierIndividualApi;
import io.swagger.client.model.store.Tier;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for ThrottlingTierIndividualApi
 */
@Ignore
public class ThrottlingTierIndividualApiTest {

    private final ThrottlingTierIndividualApi api = new ThrottlingTierIndividualApi();

    
    /**
     * Get details of a tier 
     *
     * This operation can be used to retrieve details of a single tier by specifying the tier level and tier name. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void tiersTierLevelTierNameGetTest() throws ApiException {
        String tierName = null;
        String tierLevel = null;
        String xWSO2Tenant = null;
        String accept = null;
        String ifNoneMatch = null;
        String ifModifiedSince = null;
        Tier response = api.tiersTierLevelTierNameGet(tierName, tierLevel, xWSO2Tenant, accept, ifNoneMatch, ifModifiedSince);

        // TODO: test validations
    }
    
}
